apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-engine
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web
  template:
    # name: content-engine-pod
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: my-container
          # docker pull jmitchel3/content-engine:latest
          image: jmitchel3/content-engine:latest
          env:
            - name: PORT
              value: "8080"
            - name: VERSION
              value: "1.0.3"
            - name: WELCOME_MSG
              valueFrom:
                configMapKeyRef:
                  name: content-engine-configmap
                  key:  WELCOME_MSG
          # envFrom:
          #   - configMapRef:
          #       name: django-configmap
          envFrom:
            - secretRef:
                name: content-engine-secret
          ports:
            - containerPort: 8080