[[build.env]]
name = "DISABLE_COLLECTSTATIC"
value = "1"

[[build.env]]
name =  "GOOGLE_RUNTIME_VERSION"
value = "3.11.7"

[[build.env]]
name = "GOOGLE_ENTRYPOINT"
value = "python manage.py migrate --no-input && gunicorn cfehome.wsgi:application --bind \"0.0.0.0:$PORT\""